### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by krzyzanowskim** [Zewo/Digest#3]
Hi, I hope you well. 

Mind update documentation to meet the requirements of licence of code you copied ? Thanks.

https://github.com/Zewo/Digest/blob/master/Sources/SHA1.swift#L9
"If you use this software in a product, an acknowledgment in the product documentation is required."

**Comment by scottbyrns** [comment]
Does the readme footer satisfy this for you?

https://github.com/Zewo/Digest/blob/master/README.md

**Comment by krzyzanowskim** [comment]
Thanks Scott, I appreciate that.

Link to the original repo would be awesome, if possible.

**Comment by scottbyrns** [comment]
Linked!
